version: '2'
services:
    mysql_db:
        image: mysql:5.6
        restart: always
        networks: 
          - proxy_network
        ports:
            - 3306:3306
        volumes:
            - ./db-init/init.sql:/docker-entrypoint-initdb.d/init.sql
            - ./mysql-data:/var/lib/mysql
        environment:
            TZ: Asia/Taipei
            MYSQL_ROOT_PASSWORD: 2020aiot
            MYSQL_DATABASE: Scrapy
            MYSQL_USER: arthutibame
            MYSQL_PASSWORD: 2020aiot

    proxy-scylla:
      image: wildcat/scylla:1.1.7
      container_name: proxy-scylla
      networks: 
        - proxy_network
      restart: always
      ports:
        - 8899:8899
        - 8081:8081
      volumes: 
        - ./scylla:/var/www/scylla
networks: 
  proxy_network:
    driver: bridge               