FROM python:3.6
LABEL maintainer="arthur.sl.lin@modovision.com"
COPY ./proxy_scraper_mysql /proxy_scraper_mysql
WORKDIR /proxy_scraper_mysql
RUN pip install -r requirements.txt
ENTRYPOINT [ "scrapy" ]
CMD [ "crawl proxy" ]